import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './lib/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <h1>Layout from Root</h1>
          <Header />
          {children}
        </div>
        </body>
    </html>
  )
}
